apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hketest
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: hketest
    spec:
      containers:
      - name: hketest
        image: docker.io/pleungdev/hketrain-aser:$BUILD_ID
        ports:
        - containerPort: 40041
---
apiVersion: v1
kind: Service
metadata:
  name: hketest
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: hketest
